services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://postgres:password@db/shop
    depends_on:
      - db

volumes:
  db_data: